### ISSUE TITLE
Q: "no such session" error on my Travis CI

### ISSUE THREAD

**Issue by hajimehoshi** [myitcv/gjbt#11]
I'm trying to use gjbt for my lib Ebiten Travis CI test, but I couldn't understand the failure reason. I'd appreciate if you could help me. Thank you!

.travis.yml: https://github.com/hajimehoshi/ebiten/blob/1c78bdc8fb72e21e85c7225d369edbbbf30637f9/.travis.yml

Result: https://travis-ci.org/hajimehoshi/ebiten/builds/381770310

```
2.79s$ gjbt github.com/hajimehoshi/ebiten
ok  	github.com/hajimehoshi/ebiten	0.241s
panic: failed to retrieve logs: unexpected response: {"sessionId":"c70549813356b6de15d4563dca60c4a5","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.4.0-101-generic x86_64)"}}
goroutine 1 [running]:
main.main.func1(0xc420063f10, 0xc42001c084, 0x35, 0xc420149e9f, 0xc42008ac40)
	/home/travis/gopath/src/myitcv.io/gjbt/main.go:186 +0xa6f
main.main()
	/home/travis/gopath/src/myitcv.io/gjbt/main.go:204 +0x4f2
```

**Comment by myitcv** [comment]
I wouldn't mind betting this is because you're inadvertently using an old Chrome version.

To test, add a `google-chrome --version` to your `.travis.yml`; my guess is that it will show `62.xxx`

To fix this, you need to explicitly add:

```
addons:
  chrome: stable
```

(or `beta`).

You can of course use a build matrix if required, e.g. https://github.com/myitcv/gjbt/blob/master/.travis.yml

**Comment by myitcv** [comment]
Related is https://github.com/travis-ci/travis-ci/issues/9645

**Comment by hajimehoshi** [comment]
Yeah, adding `addon` solved this. Thank you!
